### ISSUE TITLE
Combo points on Focus Frame

### ISSUE THREAD

**Issue by Dusky1** [Schaka/ArenaLive-TBC#1]
Often some combo points are added to Focus Frame. You can delete them with /clearfocus and /focus again

edit: 

1) combo points ARE NOT added/removed to/from your focus frame when u cast something via /cast [target=focus] when not targeting your focus.
2) combo points DOES NOT disappear from your focus frame when u get cobo points on another target

**Comment by Schaka** [comment]
WoWAPI doesn't support this properly for TBC. I have only added them to the focus frame, so you could keep track of how many you have, if you switch your target.
