### ISSUE TITLE
PartyFrames bug

### ISSUE THREAD

**Issue by ChekistNSK** [Schaka/ArenaLive-TBC#10]
Can't move/turn off/something else ...
https://imgur.com/a/g2rn5

**Comment by Schaka** [comment]
Have you used/tried any previous version of ArenaLive? I can't reproduce this and unless you are pasting a Lua error here, I can't begin to imagine what could cause this.

My go-to-advice: Delete ArenaLive.lua and ArenaLiva.lua.bak from your WTF/account/accountname/SavedVariables while your game is turned off. Log back into the game.
Do NOT enable arena frames in ArenaLive. They don't work - arena units don't exist in TBC and I only left the base code for the frames in, just in case any server ever came out that wanted to support arena frames through server side addon messages.
