### ISSUE TITLE
Moving cast bars?

### ISSUE THREAD

**Issue by ujellyx** [Schaka/ArenaLive-TBC#13]
Is it possible to move e. g. the focus castbar to a position of choice and not have it fixed above/below the frame?

**Comment by Schaka** [comment]
You would have to move them through editing the XML files. Depending on how popular Netherwing ends up being, I might backport ArenaLive 3 (the version I currently have released for WotLK) to TBC. It has maaaany more options, but right now ArenaLive doesn't seem popular enough for me to go through that effort.
