### ISSUE TITLE
Power bar color not corresponding with class

### ISSUE THREAD

**Issue by wyrrcz** [Schaka/ArenaLive-TBC#14]
Hi,
I am using ArenaLive UF and I am facing an issue. The power bar color is not corresponding with class (rage-red, mana-blue, energy-yellow). All of the powers have blue color (see attached picture). 
![arenalive_powerbar](https://user-images.githubusercontent.com/55812537/79573753-68962280-80bf-11ea-9f75-d75e55944737.png)
I did not find any option to configure the power bar color. Does anyone have an idea, what causes this issue?

Thx

**Comment by Schaka** [comment]
I have not been able to reproduce this. However, another user got this issue because he had mixed his classic wow folder with TBC. You probably did too.

**Comment by wyrrcz** [comment]
Hi,
somehow, the issue was caused by interferrence with Gladdy addon (maybe I downloaded wrong version, idk...)
SOLUTION:
1) I just deleted the Gladdy lua settings from:
WTF\Account\Account_name\SavedVariables
WTF\Account\Account_name\Server_name\Character_name\SavedVariables
2) I deleted the Gladdy addon folder from \Interface\Addons
3) Then, I downloaded gladdy for 2.4.3 from here:
https://bestwowaddons.com/download/gladdy/
4) Put the downloaded Gladdy addon in Addons folder
5) Run game, ArenaLive works flawlessly now
6) Configure Gladdy addon again as its lua config has been deleted in 1)
7) Done

Thanks.

**Comment by Schaka** [comment]
You probably noticed I maintain the current fork of Gladdy, so you should get it from my repo.
Thanks for the info though
