### ISSUE TITLE
Target/Focus Healthbar option

### ISSUE THREAD

**Issue by Dusky1** [Schaka/ArenaLive-TBC#2]
I would like to have an "reaction" option (red for enemy, green for friendly) for target/targettarget/focus/focustarget healtbars colors.

**Comment by Schaka** [comment]
This was already in, actually. But the index for the optionsmenu was duplicated, so it got lost.
Fixed in: https://github.com/Schaka/ArenaLive-TBC/commit/9299581da127774a03752bc2dedb8587f8933ea6
