### ISSUE TITLE
Tag issue.

### ISSUE THREAD

**Issue by vasecha** [Schaka/ArenaLive-TBC#4]
Hello. 
As it says, addon doesnt show who tags the mob first - me or someone else. Thats pretty sad when you are lvling. Ofc this addon was made mainly for PvP... but...
Can anything be done about it?
Thank you in advance.

**Comment by Schaka** [comment]
Are you maybe using some other addon interfering with ArenaLive? I use ArenaLive while leveling and the enemy name is grey, if they are tagged by someone else.

**Comment by vasecha** [comment]
Oh..sorry, my bad. Only the targets name becomes gray, not the unitframe itself. Just noticed. =(
I think that for npсs markng complete unitframe would be better, but its not so important.
Thank you!
