### ISSUE TITLE
How can I remove the black shades/gradient on the healthbars?

### ISSUE THREAD

**Issue by lastnoob** [Schaka/ArenaLive-TBC#5]
This is more like a question not an issue, but I'm looking for a more materialistic (as in material design) healthbar. I checked the textures but there doesn't seem to be a gradient or extra shadow.

So how can I remove it? I want it to be just a simple color.

**Comment by Schaka** [comment]
It uses default textures, so replacing them in your Interface folder will do the trick.

**Comment by lastnoob** [comment]
Sorry for bothering you, but in my Interface folder (which only contains the AddOns folder) I can't find a relevant blizzard addon for this.

And my /Data/enUS/Interface folder only contains the cinematics, nothing more. Could you help me out by just telling me what folder should I look at exactly, please?

Otherwise I love you addons, I use several of them! Thanks

**Comment by Schaka** [comment]
That's because by default, those files are in your MPQ files (in Data). If you create the same structure in your Interface folder and name the files the same, the game automatically picks them up and overwrites the original.

You can look at SchakaPvPUI for an example
