### ISSUE TITLE
Pet happiness

### ISSUE THREAD

**Issue by kingmru** [Schaka/ArenaLive-TBC#6]
is there a way to show pet happiness icon next to a pet frame?

**Comment by Schaka** [comment]
Good point, I'll have to add it.

**Comment by ChekistNSK** [comment]
> Good point, I'll have to add it.

I'm sorry, you'll be adding or ...

**Comment by Schaka** [comment]
No. It makes no sense since all TBC private servers don't really degrade happiness in arena. I'll add it for the retail TBC version eventually.
