### ISSUE TITLE
Default frames not hidden

### ISSUE THREAD

**Issue by nemspec** [Schaka/ArenaLive-TBC#7]
Hi!

On the first install everything worked perfectly, but after a restart the default blizzard unit frames are still visible while using the ArenaLive frames.

Also the party frames are always visible (but empty) even when not in a party.

**Comment by nemspec** [comment]
Completely deleting any config files from WTF resetted it.

**Comment by Schaka** [comment]
In the future, if anything similar happens, it's enough to go into your WTF/.../SavedVariables folder and deleting all ArenaLive.lua and ArenaLive.lua.bak files you can find there.

**Comment by nemspec** [comment]
Should have been more precise, that is what I did (only deleted ArenaLive files).
However, this comes with the downside of losing your configuration obviously.
