### ISSUE TITLE
Addon request

### ISSUE THREAD

**Issue by me0wg4ming** [Schaka/ArenaLive-TBC#8]
This message is for the user: "Schaka"

Guten morgen, wäre es möglich sich mal wo zu unterhalten?
Ich hätte gerne ein addon von WOTLK für TBC - ich würde auch dafür was bezahlen.
Viel. kann man sich mal privat unterhalten?

Der addon name ist: "Spy" - ist ein world pvp addon und vermisse ich in tbc doch sehr...
Ich weiss es gibt eins das nennt sich "Paranoia" aber das ist nicht mal ansatzweise so gut....

Meine e-mail: welpenhund84@gmail.com - Gerne auch über andere platformen... bin auch im warmane forum mit dem namen holyhorror

**Comment by Schaka** [comment]
Discord: https://discord.gg/BJ9HRyz
